name: Build_deploy
on: [push]
jobs:
  build_push:
    runs-on: ubuntu-latest
    steps:
      - name: list directory
        run: ls -la
      - name: clone code
        uses: actions/checkout@v2
      - name: list directory 2
        run: ls -la