name: Build_deploy
on: [push]
jobs:
  build_push:
    runs-on: ubuntu-latest
    steps:
      - name: clone code
        uses: actions/checkout@v2
      - name: docker build
        run: docker build -t stashunter/flask-app:$GITHUB_REF_NAME-$GITHUB_RUN_ID .